services:
  spp-frontend-production:
    container_name: spp-frontend-production
    network_mode: host
    build:
      target: production
      context: .
      args:
        - PORT=${PORT:-3000}
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=${PORT:-3000}
      # Variables de aplicación (se pueden sobrescribir)
      - NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL:-http://localhost:3000}
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL:-http://localhost:3001}
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          cpus: '0.25'
          memory: '256m'


