name: '👋 Greetings'

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ¡Hola @${{github.actor}} 👋!

            ¡Gracias por abrir tu primer issue aquí! ♥️
            Si estás reportando un bug 🐞, por favor asegúrate de incluir pasos sobre cómo reproducirlo.

            Lo revisaremos tan pronto como podamos 💪
          pr-message: |
            ¡Hola @${{github.actor}} 👋!

            ¡Gracias por estar aquí y ayudar a que este proyecto crezca 🚀
            Lo revisaremos tan pronto como podamos :D

            Por favor revisa nuestras guías de contribución mientras tanto 📃

