name: 🙊 Typos

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check-typos:
    name: Check for Typos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v6

      - name: Check typos 🔍
        uses: crate-ci/typos@v1.38.1
        with:
          config: ./_typos.toml

